name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.16.1]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build
        npm run deb64
      env:
        CI: true
    - name: upload built artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: ./dist
